spring:
  application:
    name: cloud-zuul-getway
  cloud:
    gateway:
      routes:
        id: service-1
        uri: http://localhost:8001
        predicates:
          -path=/service-1
  redis:
    host: 192.168.133.129
    port: 6379
    password: syh123
    database: 0
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

server:
  port: 8003

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
